name: Android CI/CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      # Checkout Source
      - name: Checkout Source
        uses: actions/checkout@v4

      # Setup Java
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Setup Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      # Gradle Permission
      - name: Grant Execute Permission
        run: chmod +x gradlew

      # Cache Gradle
      - name: Cache Gradle Files
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      # Decode google-services.json
      - name: Decode google-services.json
        run: |
          echo "${{ secrets.GOOGLE_SERVICES_JSON }}" | base64 --decode > app/google-services.json

      # Run Lint
      - name: Run Lint Check
        run: ./gradlew lint

      # Run Unit Tests
      - name: Run Unit Tests
        run: ./gradlew test

      # Build Debug APK
      - name: Build Debug APK
        run: ./gradlew assembleDebug

      # Build Release APK
      - name: Build Release APK
        run: ./gradlew assembleRelease

      # Build Release AAB
      - name: Build Release Bundle
        run: ./gradlew bundleRelease

      # Upload Debug APK Artifact
      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

      # Upload Release APK Artifact
      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: app/build/outputs/apk/release/app-release.apk

      # Upload AAB Artifact
      - name: Upload Release AAB
        uses: actions/upload-artifact@v4
        with:
          name: release-aab
          path: app/build/outputs/bundle/release/app-release.aab

      # Firebase Distribution
      - name: Upload APK to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          groups: testers
          file: app/build/outputs/apk/debug/app-debug.apk
